// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT1lhhmkbdfshU9Kr8y-O6uHJHRfp3Mog',
    appId: '1:364080245203:web:4fecd56cfa4c0fb956e726',
    messagingSenderId: '364080245203',
    projectId: 'test-firebase-23b71',
    authDomain: 'test-firebase-23b71.firebaseapp.com',
    storageBucket: 'test-firebase-23b71.appspot.com',
    measurementId: 'G-20VQMFPX19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZaejLmY4aDxzIVlZ3qDL5sOnJiEpXhvA',
    appId: '1:364080245203:android:e402182e9f16ee6556e726',
    messagingSenderId: '364080245203',
    projectId: 'test-firebase-23b71',
    storageBucket: 'test-firebase-23b71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxyfooKG39sAB0vaij50RLfOD6tnTyXR0',
    appId: '1:364080245203:ios:ca2e93f5207df7a756e726',
    messagingSenderId: '364080245203',
    projectId: 'test-firebase-23b71',
    storageBucket: 'test-firebase-23b71.appspot.com',
    iosBundleId: 'com.abtech.brewCrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxyfooKG39sAB0vaij50RLfOD6tnTyXR0',
    appId: '1:364080245203:ios:ca2e93f5207df7a756e726',
    messagingSenderId: '364080245203',
    projectId: 'test-firebase-23b71',
    storageBucket: 'test-firebase-23b71.appspot.com',
    iosBundleId: 'com.abtech.brewCrew',
  );
}
